[server]
enableCORS = false
enableXsrfProtection = false

[logger]
level = "error"

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[runner]
fastReruns = true
magicEnabled = false
postScriptGC = true 